"""
Olym Matrix: Porosity Gradient Drive Simulation Framework
Author: Ashraf Olym (Olym Era)
Description: 
This core module simulates subluminal warp propulsion through mechanical fluidic displacement
in a viscoelastic vacuum. It supersedes general-relativistic 'negative energy' constraints
by manipulating the structural porosity of spacetime.
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import logging

# Configure professional logging for execution output
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class OlymWarpDrive:
    """
        The fundamental engine class for the Olym Matrix framework.
            Manages the kinematic-geometric coupling required for fluidic displacement propulsion.
                """
                    
                        def __init__(self, k: float = 1.0, G: float = 1.0) -> None:
                                """
                                        Initializes the Olym Drive with necessary cosmic constants.
                                                
                                                        Args:
                                                                    k (float): Dimensional scaling constant for mass alignment.
                                                                                G (float): Cosmic Stiffness constant resisting the kinematic pulse.
                                                                                        """
                                                                                                # Fundamental Kinematic Driver (Event Pulse) in m/s (Equivalent to c)
                                                                                                        self.V_plus: float = 299792458.0 
                                                                                                                
                                                                                                                        # Scaling parameters
                                                                                                                                self.k: float = k  
                                                                                                                                        self.G: float = G  
                                                                                                                                                
                                                                                                                                                        logging.info("OlymWarpDrive initialized with V+ = 299792458 m/s")

                                                                                                                                                            def calculate_velocity(self, P_stern: np.ndarray, P_bow: np.ndarray) -> np.ndarray:
                                                                                                                                                                    """
                                                                                                                                                                            Calculates the propulsion velocity based on the porosity differential.
                                                                                                                                                                                    Equation: v = V^+ * (P_stern - P_bow)
                                                                                                                                                                                            
                                                                                                                                                                                                    Args:
                                                                                                                                                                                                                P_stern (np.ndarray): Porosity at the stern of the warp bubble (repulsion).
                                                                                                                                                                                                                            P_bow (np.ndarray): Porosity at the bow of the warp bubble (congestion).
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                Returns:
                                                                                                                                                                                                                                                            np.ndarray: The resulting velocity in m/s.
                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                            # Calculate Porosity Gradient
                                                                                                                                                                                                                                                                                    delta_P = P_stern - P_bow
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                    # Velocity cannot be negative (in this specific thrust vector) and cannot exceed V^+
                                                                                                                                                                                                                                                                                                            delta_P = np.clip(delta_P, 0.0, 1.0) 
                                                                                                                                                                                                                                                                                                                    velocity = self.V_plus * delta_P
                                                                                                                                                                                                                                                                                                                            return velocity

                                                                                                                                                                                                                                                                                                                                def calculate_impedance(self, P_local: np.ndarray) -> np.ndarray:
                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                Calculates the derived mechanical impedance (inertial mass) from local porosity.
                                                                                                                                                                                                                                                                                                                                                        Equation: m = (k * V^+) / (G * P_local)
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                        Args:
                                                                                                                                                                                                                                                                                                                                                                                    P_local (np.ndarray): The structural porosity of the localized medium.
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                        Returns:
                                                                                                                                                                                                                                                                                                                                                                                                                    np.ndarray: Mechanical impedance resolving to the SI unit (kg).
                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                    # Prevent division by absolute zero to maintain mathematical stability
                                                                                                                                                                                                                                                                                                                                                                                                                                            # Minimum porosity (0.001) represents extreme structural congestion (e.g., Event Horizon)
                                                                                                                                                                                                                                                                                                                                                                                                                                                    P_local = np.clip(P_local, 0.001, 1.0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            mass_impedance = (self.k * self.V_plus) / (self.G * P_local)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return mass_impedance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def verify_structural_resonance(self, R_boundary: float) -> float:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Deterministically calculates the structural resonance frequency for a given
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rigid geometric boundary (where Porosity P approaches 1 congestion).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Equation: f_res = V^+ / R_boundary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            f_res = self.V_plus / R_boundary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logging.info(f"Structural Resonance calculated for radius {R_boundary}m: {f_res:.2f} Hz")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return f_res


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def execute_comprehensive_simulation():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Executes the full suite of Olym Matrix simulations and generates 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        academic-grade visualizations for publication and peer review.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logging.info("Starting comprehensive Olym Matrix simulation suite...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Initialize the core engine
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            olym = OlymWarpDrive()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # --- 1. THE EMPIRICAL PROOF (1639 Hz) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Target: GW150914 post-merger remnant rigid boundary
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        R_s_gw150914 = 182911.8 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            f_res = olym.verify_structural_resonance(R_boundary=R_s_gw150914)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"\n[EMPIRICAL PREDICTION] Expected mechanical resonance for GW150914 remnant: {f_res:.2f} Hz\n")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # --- 2. DATA GENERATION FOR VISUALIZATION ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Generate 1D arrays for 2D plots
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            porosity_gradient_1d = np.linspace(0.0, 1.0, 500)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                velocity_1d = olym.calculate_velocity(porosity_gradient_1d, 0.0) / olym.V_plus
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local_porosity_1d = np.linspace(0.01, 1.0, 500)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mass_impedance_1d = olym.calculate_impedance(local_porosity_1d)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Generate 2D grids for 3D Surface plot
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    P_bow_grid = np.linspace(0.0, 1.0, 100)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        P_stern_grid = np.linspace(0.0, 1.0, 100)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            P_bow_mesh, P_stern_mesh = np.meshgrid(P_bow_grid, P_stern_grid)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Calculate velocity across the entire 3D mesh matrix
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        velocity_mesh = olym.calculate_velocity(P_stern_mesh, P_bow_mesh) / olym.V_plus

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # --- 3. ACADEMIC VISUALIZATION (MATPLOTLIB) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logging.info("Rendering high-fidelity academic plots...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Set up a large figure with a modern academic style
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            plt.style.use('seaborn-v0_8-darkgrid')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fig = plt.figure(figsize=(18, 6))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fig.suptitle("Olym Matrix: Subluminal Porosity Gradient Propulsion Mechanics", fontsize=18, fontweight='bold', y=1.05)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # SUBPLOT 1: 2D Velocity vs Gradient
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ax1 = fig.add_subplot(1, 3, 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ax1.plot(porosity_gradient_1d, velocity_1d, color='#1f77b4', linewidth=2.5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ax1.fill_between(porosity_gradient_1d, velocity_1d, color='#1f77b4', alpha=0.2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ax1.set_title(r"Fluidic Displacement Velocity", fontsize=14)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ax1.set_xlabel(r"Porosity Gradient ($\Delta P$)", fontsize=12)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ax1.set_ylabel(r"Velocity (Fraction of $V^+$)", fontsize=12)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ax1.grid(True, linestyle='--', alpha=0.6)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # SUBPLOT 2: 2D Mass Impedance (Log Scale)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ax2 = fig.add_subplot(1, 3, 2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ax2.plot(local_porosity_1d, mass_impedance_1d, color='#d62728', linewidth=2.5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ax2.set_title(r"Derived Mass Impedance vs Porosity", fontsize=14)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ax2.set_xlabel(r"Local Porosity ($P$)", fontsize=12)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ax2.set_ylabel("Mechanical Impedance (kg) [Log Scale]", fontsize=12)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ax2.set_yscale('log')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ax2.grid(True, linestyle='--', alpha=0.6)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # SUBPLOT 3: 3D Surface Plot of Bow vs Stern Interaction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ax3 = fig.add_subplot(1, 3, 3, projection='3d')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                surface = ax3.plot_surface(P_bow_mesh, P_stern_mesh, velocity_mesh, cmap='viridis', edgecolor='none', alpha=0.9)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ax3.set_title("3D Velocity Matrix mapping", fontsize=14)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ax3.set_xlabel('Bow Porosity (Congestion)', fontsize=10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ax3.set_ylabel('Stern Porosity (Free Space)', fontsize=10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ax3.set_zlabel(r'Velocity ($v/V^+$)', fontsize=10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fig.colorbar(surface, ax=ax3, shrink=0.5, aspect=10, pad=0.1, label='Velocity Magnitude')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Finalize and Save
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            plt.tight_layout()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                file_name = "Olym_Matrix_Comprehensive_Simulation.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    plt.savefig(file_name, dpi=300, bbox_inches='tight')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logging.info(f"Simulation visualizations successfully saved as '{file_name}' at 300 DPI.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Display the plot window
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    plt.show()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("="*60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("OLYM MATRIX - COMPUTATIONAL PHYSICS ENGINE INITIALIZING")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("="*60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    execute_comprehensive_simulation()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("="*60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("EXECUTION COMPLETE.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("="*60)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                